### ISSUE TITLE
removing events from childchain prototype test cases

### ISSUE THREAD

**Issue by Clearwood** [leapdao/nervos#10]
# Bounty

Forking out the work of removing Events from the [tests of the child-chain prototype](https://github.com/leapdao/nervos/issues/8).
## Scope

- Getting tests to work and creating issues
- open issues for errors with event scanning and other Ethereum incompatibility of Ethermint.

## Deliverables

-working code

## Roles
bounty gardener + worker: @Clearwood 
bounty reviewer: / 30 DAI

## Gardener checklist

- [ ] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by Clearwood** [comment]
- https://github.com/ChainSafe/ethermint/issues/489
- https://github.com/ChainSafe/ethermint/issues/490

**Comment by TheReturnOfJan** [comment]
Verified.
