### ISSUE TITLE
startup script for child chain

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/nervos#11]
`#` Bounty

the deployment of the parent chain bridge, and the startup of the child chain validators need to be synchronized. figure out how to do it in as few steps as possible.

## Scope

- validator addresses need to be known in parent chain contract to verify burn proofs
- validators need to be entered into genesis file of child chain
- bridge contract needs to be deployed on child chain start and funded with all supply
- validators need to have gas on child chain, to be able to relay events
- child chain balance (funds outside of the bridge contract) should never exceed capacity of the bridge

## Deliverables

- startup script
- ~~written instructions reproducible by any-one's grandma~~ forked to https://github.com/leapdao/nervos/issues/29

## Bounty Owner/Gardener

@johannbarbie as childChainDevLink

## Roles
bounty gardener: @johannbarbie 10%
bounty worker: @Clearwood  / 75%
bounty reviewer: @johannbarbie  / 15%

## Gardener checklist

- [ ] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by Clearwood** [comment]
https://github.com/leapdao/nervos/pull/30
