### ISSUE TITLE
Implement deploy state transition in parent-bridge

### ISSUE THREAD

**Issue by TheReturnOfJan** [leapdao/nervos#12]
# Bounty

## Scope

- A state transition for bridge deployment
- Verifies validator list
- Verifies state identity

## Deliverables

- Code

## Funding Circle

Nervos

## Bounty Owner/Gardener

<@TheReturnOfJan> as **CKB Dev Lead**

## Gain for the Role

Bringing the bridge closer to life

## Roles
bounty gardener: <@TheReturnOfJan> / 0 DAI 
bounty worker: @TheReturnOfJan / 90% 
bounty reviewer: @johannbarbie  / 10% 

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by johannbarbie** [comment]
(![parentBridgeTxns (1)](https://user-images.githubusercontent.com/659301/92739281-03e4a880-f37d-11ea-8b24-e858fd740fa6.png))[https://github.com/leapdao/nervos/blob/master/docs/parentBridge.md]
