### ISSUE TITLE
Implement deposit lock script

### ISSUE THREAD

**Issue by TheReturnOfJan** [leapdao/nervos#17]
# Bounty

## Scope

- We need a lock script for deposits
- It unlocks either with a signature of the depositor, or if it is being spent by bridge typescript with id

## Deliverables

- The contract
- Some unit tests

## Funding Circle

Nervos

## Bounty Owner/Gardener

@TheReturnOfJan  as CKB Dev Lead
## Roles
bounty gardener: @TheReturnOfJan  / 50 DAI 
bounty worker: @TheReturnOfJan  / 80%
bounty reviewer: name / share

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by johannbarbie** [comment]
[![parentBridgeTxns (2)](https://user-images.githubusercontent.com/659301/92739751-81101d80-f37d-11ea-9f69-3d51df9b7b0b.png)](https://github.com/leapdao/nervos/blob/master/docs/parentBridge.md)
