### ISSUE TITLE
Investigate tendermint hash function for nervos

### ISSUE THREAD

**Issue by TheReturnOfJan** [leapdao/nervos#2]
# Bounty
Ethermint is built on top of tendermint, which uses some signature scheme in signing block headers etc. Find out what this scheme is a come up with a plan on how to use it on nervos.

## Scope

- Find out all the relevant details about signatures on tendermint
- Investigate the options of using tendermint-style sigs on nervos i.e.
1.) Are the required cryptographic primitives already available as nervos cells?
2.) If not, come up with a plan to compile and deploy the right ones in this [repo](https://github.com/tendermint/signatory)

## Deliverables

- An issue in this repo, with details on how to proceed

## Funding Circle

Nervos Circle.
## Gain for the Role

Progress.
## Roles
bounty gardener: @TheReturnOfJan  / 50 DAI 
bounty worker: name  / share
bounty reviewer: name / share

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by johannbarbie** [comment]
option 1: implement blake2 in solidity:
- blake2b hash function used on nervos.
- istanbul added blake2b compression to Ethereum, now blake2b hashing can be implemented in solidity.

option 2: deploy sha3 on nervos:
- throw it into the binary at the beginning
- use dependency cells once rust supports "dynamic loading"

**Comment by johannbarbie** [comment]
@TheReturnOfJan is this something that could be paid out based on the progress you have made yesterday?

**Comment by TheReturnOfJan** [comment]
Yes.
