### ISSUE TITLE
documentation for child chain startup script

### ISSUE THREAD

**Issue by Clearwood** [leapdao/nervos#29]
# Bounty
Forked from #11 to account for difficulties parallelizing to run the Ethermint chain and the RPC server as well as distributing the initial amounts to the validators.  

## Scope

- written instructions reproducible by any-one's grandma
- in what order are the different systems deployed (parent bridge, validators, genesis file, childchain)
- how is the genesis file generated, without exposing the validator private keys to single machine?
- how do the validator machines discover each other, and start validating first blocks?

## Deliverables

- written instructions reproducible by any-one's grandma
- updated documentation

## Funding Circle

Nervos 

## Bounty Owner/Gardener

<@your github username> as **<Role>**

@Clearwood as Child Chain Dev Lead

## Roles
bounty gardener: @Clearwood / 467.5 DAI 
bounty reviewer:  / 82.5 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by johannbarbie** [comment]
the scope here is very short. 
I have a few open questions:
in what order are the different systems deployed (parent bridge, validators, genesis file, childchain)
how is the genesis file generated, without exposing the validator private keys to single machine?
how do the validator machines discover each other, and start mining on the first block?

**Comment by eshavkun** [comment]
@Clearwood I agree that some expanding of both deliverable and scope is needed. Otherwise, any script that can be executed `by any-one's grandma` will fit into it.

**Comment by mwaa** [comment]
Questions moved to new forked [issue 42 ](https://github.com/leapdao/nervos/issues/42)
