### ISSUE TITLE
invalid tuple value (coderType="tuple", value="")

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/nervos#38]
# Bounty

source: Issue #28 

## Scope

when trying to send structs through external interfaces ([see test](https://github.com/leapdao/nervos/tree/fix/codestyle)) the following error occurs:
```
 1) Contract: Bridge
       should allow and collect unlock signatures:
     Error: invalid tuple value (coderType="tuple", value="0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000fc5bc8373d2b91c646f23b4d90597db777adcf800000000000000000000000000000000000000000000000001bc16d674ec80000638047d47000c6c565bc987f4ded73cb9068863fbf4d782b39b8328e140149f8")
      at Context.<anonymous> (test/bridge.js:46:23)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

thesis: structs in external interfaces not supported by either truffle or web3.

blocking https://github.com/leapdao/nervos/issues/28

## Deliverables

- Working tests and new code

## Roles
bounty gardener: 0 DAI
bounty worker:  @mwaa 325 DAI
bounty reviewer: name / 25 DAI

**Comment by TheReturnOfJan** [comment]
This can be fixed by marking the method as public rather than external.

**Comment by mwaa** [comment]
Work
- Evaluated ethers js as an alternative to use
- Investigated library inconsistencies between ethers, web3, and ethereum-utils
- Evaluated the logic used

Product
- Fixed tests in PR
- Using only web3 for consistency
- There is an issue with BigNumber encoding for uint256 instead use hexNumber
- Logic no need to encode parameters if we are not passing the hash string as a function parameter. Instead just pass the object
