### ISSUE TITLE
Investigate validator signing functionality for the relayer service

### ISSUE THREAD

**Issue by mwaa** [leapdao/nervos#39]
# Bounty
Relayer service needs validator to sign for transactions before they are relayed across chains.

## Scope

- Check on the security of having the private key as an environment variable
- Evaluate how other cosmos modules implement this part
- Check if ethermint exposes a signing functionality for validators

## Deliverables

- Rewrite of the #26 
- Note on security functionality

## Funding Circle
Nervos

## Roles
bounty gardener: @mwaa  /  40 DAI 
bounty worker: @mwaa  / 250 DAI
bounty reviewer: @johannbarbie  / 60 DAI

## Gardener checklist

- [ ] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by mwaa** [comment]
Findings:
1. Other relayer services such as the cosmos module peggy require that private key be stored as OS environment variable. 

> Been a module it still has no direct access to the private key hence still needs to relay on environment variable
> Peggy implemented  with oracle functionality and has two steps. relay transaction then later transaction to sign relayed transactions compared to our single step of relay transaction
> Peggy contracts just check the validator address is within the validator set and not the signatures.

2. Ethermint permits the current validator to send transactions and signs them from memory since it unlocks the private key during start of rpc server. Find below code example requires node & server to be up and running

3. On security issue. 
> Point 2 above prevents duplication of having private key as environment variable.
> Its up to the validator to protect the node environment such as https endpoints and DDOS protections. 

Final delivery forked task to #26 and #40 

```javascript
const Web3 = require('web3');
const { promisify } = require('util');
const web3 = new Web3('http://localhost:8545');
const exec = promisify(require('child_process').exec)

// This has to be the key passed during start of rpc server
// can be passed during startup based on validator key
let validator = 'mykey';  

async function getValidatorAddress () {
    let data = await exec(`ethermintcli q auth account $(ethermintcli keys show ${validator} -a) -o json`);
    data = JSON.parse(data.stdout);
    return data.value.eth_address;
};

async function signExample() {
    let validatorAddress = await getValidatorAddress();
    validatorAddress = validatorAddress.toLowerCase();
    let signedMessage = await web3.eth.personal.sign('Hello world', validatorAddress, 'password!');
    let verifyAddress = await web3.eth.personal.ecRecover('Hello world', signedMessage);

    console.log('Validator Address', validatorAddress);
    console.log('Verify Address', verifyAddress);
    return verifyAddress == validatorAddress;
}

async function transferExample() {
    let validatorAddress = await getValidatorAddress();
    let newAddress = await web3.eth.personal.newAccount('!@superpassword');
    let oldBalance = await web3.eth.getBalance(newAddress);
    console.log('Old Balance', oldBalance);
    // Password is not needed because the key was unlocked during start of server
    // ethermintcli rest-server --laddr 'tcp://localhost:8545' --unlock-key mykey --chain-id 8
    await web3.eth.sendTransaction({
        from: validatorAddress,
        gasPrice: '20000000000',
        gas: '21000',
        to: newAddress,
        value: '1000000000000000000',
        data: ''
    }, ''); 
    let balance = await web3.eth.getBalance(newAddress);
    console.log('New Balance', balance);
    return balance != 0;    
}

async function runExamples() {
    console.log('Validator address is able to sign message', await signExample());
    console.log('\n');
    console.log('Validator address is able to send Transaction', await transferExample());
}

runExamples();


```

**Comment by johannbarbie** [comment]
great work testing the wallet here and finding a simple way to use the validator address 👏
