### ISSUE TITLE
design doc for child chain

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/nervos#4]
# Bounty

Specify the functionality of the child chain and all interfaces that would allow the interaction between parent chain and child chain.

## Scope

- setup requirements
- interface of contracts
- receipt structure 

## Deliverables

- documentation as markdown in `docs` folder of repo

## Bounty Owner/Gardener

@johannbarbie as ChildChainDevLink

## Roles
bounty gardener: @johannbarbie  / 10%
bounty worker: @johannbarbie  / 70%
bounty reviewer: @eshavkun  / 20%

## Gardener checklist

- [ ] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform

**Comment by eshavkun** [comment]
Adding myself as reviewer

**Comment by eshavkun** [comment]
Review complete
