### ISSUE TITLE
tutorial bounty for learning Rust/CKB development

### ISSUE THREAD

**Issue by Clearwood** [leapdao/nervos#7]
# Bounty

This is an individual learning bounty and will be paid out to those that complete it.
If you currently do not hold a role within the Nervos circle, talk to one of those currently holding one.

## Scope

- this bounty is supposed to reward participation in the SUDT tutorial, rewarding learnings on CKB and Rust
- tutorial: https://docs.nervos.org/docs/labs/sudtbycapsule
- go through the tutorial and 

## Deliverables

- post screenshot of deployment plan in this Github conversation e.g. 
![image](https://user-images.githubusercontent.com/11144110/89648307-4ff48700-d8bf-11ea-9154-db4eaa3d8f7a.png)

## Funding Circle

Nervos

## Roles
bounty gardener: @Clearwood / 50 DAI 
bounty worker: name / 150 DAI
bounty reviewer: channel / 0 DAI
## Gardener checklist

- [ ] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by Clearwood** [comment]
![image](https://user-images.githubusercontent.com/11144110/92007622-797dc280-ed46-11ea-9493-824c07651ef9.png)

**Comment by mwaa** [comment]
Month of August is over. This bounty is no longer available as it was meant to onboard more devs into the CKB technology stack.

**Comment by eswarasai** [comment]
```
capsule deploy --address ckt1qyq95l6gfup8nvvzfn4slezp8fyx3q9x6mjsghq6ah --fee 0.1
```

<img width="613" alt="leap-sudt" src="https://user-images.githubusercontent.com/5172086/92361307-d513cb80-f10b-11ea-8d41-f7e87c6914e8.png">
