### ISSUE TITLE
Collect deposit lumos function doesn't find cell due to lagging indexer

### ISSUE THREAD

**Issue by mwaa** [leapdao/nervos#71]
## Reproduce Steps

- Made a deposit
- Increased the sleep time to 10 minutes
- I see that the deposit is recorded as second transaction in block explorer
- Called `await client.getDeposits();()` 
- Print the cell  which is an empty array
- Pass empty array to collectDeposits
- Query bridge state but capacity is unchanged. i.e does not reflect recent deposit

## Deliverables

- `await client.getDeposits();` Should return the deposit cell to pass on to collectDeposits
- bridge state capacity reflects new balance

*Might be fixed with event emitter #64

**Comment by TheReturnOfJan** [comment]
Please try again in #74. Works for me.

**Comment by TheReturnOfJan** [comment]
Actually it was a legit bug (only happens when u deploy bridge, and not set it in config). Pushing fix in #74 .
