### ISSUE TITLE
child bridge prototype

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/nervos#8]
# Bounty

first implementation of child chain bridge.

## Scope

bridge can-dos:
- collect lock receipts
- release tokens once quorum of sigs received
- collect brun receipts
- emit event with sigs once quorum reached

## Deliverables

- contract code
- tests that pass on ethermint

## Bounty Owner/Gardener

@johannbarbie as childChainDevLink

## Roles
bounty gardener: @johannbarbie / 11%
bounty worker: @johannbarbie @Clearwood  / 37% & 37%
bounty reviewer: name / 15%

## Gardener checklist

- [ ] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by johannbarbie** [comment]
testing events in ethermint produced some problems and required a rewrite of the tests. @Clearwood will fork out an issue.

**Comment by eshavkun** [comment]
> testing events in ethermint produced some problems and required a rewrite of the tests. @Clearwood will fork out an issue.

@johannbarbie Isn't it a blocker for a proper review of this bounty?

**Comment by Clearwood** [comment]
> > testing events in ethermint produced some problems and required a rewrite of the tests. @Clearwood will fork out an issue.
> 
> @johannbarbie Isn't it a blocker for a proper review of this bounty?

The work is included in the linked PR
